### ISSUE TITLE
agri-nmp Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#1]
### List of affected namespaces:
- agri-nmp-tools

### List of volumes to migrate:
- agri-nmp-tools/jenkins-pipeline-svc (1Gi)
- agri-nmp-tools/postgresql-sonarqube-pvc (5Gi)
- agri-nmp-tools/sonarqube-data (5Gi)

**Comment by CodingVelocista** [comment]
I'm the lead Dev for this Project, can you please assign it to me @CodingVelocista.

**Comment by CodingVelocista** [comment]
@jefkel this is completed.
We actually didn't require any of the storage listed, so all were deleted and the deployment templates have all be changes to be gluster-file-db if deployed in the future.

**Comment by jefkel** [comment]
Awesome, thanks for the quick turnaround.
