### ISSUE TITLE
esm Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#16]
### List of affected namespaces:
- esm-dev
- esm-test
- esm-prod

### List of volumes to migrate:
- esm-dev/epic-master-docs-pvc (20Gi)
- esm-dev/mongodb-backup (1Gi)
- esm-prod/esm-prod-docs-pvc (200Gi)
- esm-prod/mongodb2 (10Gi)
- esm-prod/mongodb-backup (10Gi)
- esm-prod/mongodbdata (10Gi)
- esm-test/esm-test-docs-pvc (5Gi)
- esm-test/mongodbdata (5Gi)

**Comment by ActionAnalytics** [comment]
Assign this to me pls Jeff

**Comment by ActionAnalytics** [comment]
We need to have our storage quota temporary increased by 250Gi in order to get this work done.

@jefkel can you get us a temporary bump in storage?

**Comment by jefkel** [comment]
Temp quota increase confirmed/available

**Comment by ActionAnalytics** [comment]
Thank you

**Comment by MaxWardle** [comment]
Hey Jeff, I would like to increase the NFS backup storage quota to 250GB, so I can set up the automated backups. Thanks.

**Comment by ActionAnalytics** [comment]
DONE -- esm-dev/epic-master-docs-pvc (20Gi)
MARKED FOR DELETION BUT **NOT DELETING** -- esm-dev/mongodb-backup (1Gi)
PENDING (**NEXT WEEK**) -- esm-prod/esm-prod-docs-pvc (200Gi)
DONE -- esm-prod/mongodb2 (10Gi)
DONE -- esm-prod/mongodb-backup (10Gi)
DONE -- esm-prod/mongodbdata (10Gi)
DONE -- esm-test/esm-test-docs-pvc (5Gi)
DONE -- esm-test/mongodbdata (5Gi)

**Comment by jefkel** [comment]
Looks like only esm-prod-docs-pvc is left to remove, and is only attached to the migrator pod. (not in use by anything else).  

Do you have an ETA for when this PVC will be released?

**Comment by jefkel** [comment]
Verified complete.
