### ISSUE TITLE
gcpe-mygovbc-msp Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#20]
### List of affected namespaces:
- gcpe-mygovbc-msp-dev
- gcpe-mygovbc-msp-uat

### List of volumes to migrate:
- gcpe-mygovbc-msp-dev/splunk-local-log (1Gi)
- gcpe-mygovbc-msp-uat/elasticsearch-backup (1Gi)
- gcpe-mygovbc-msp-uat/jenkins (1Gi)

**Comment by evgeny-pluzhnikov** [comment]
All done.

**Comment by jefkel** [comment]
Confirmed
