### ISSUE TITLE
gcpe-mygovbc-service-provider Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#21]
### List of affected namespaces:
- gcpe-mygovbc-service-provider-dev
- gcpe-mygovbc-service-provider-tools

### List of volumes to migrate:
- gcpe-mygovbc-service-provider-dev/postgresql (1Gi)
- gcpe-mygovbc-service-provider-tools/jenkins (1Gi)

**Comment by f-w** [comment]
Migration completed. thx.

**Comment by jefkel** [comment]
Confirmed and closed.
