### ISSUE TITLE
ido-bcols Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#25]
### List of affected namespaces:
- ido-bcols-dev

### List of volumes to migrate:
- ido-bcols-dev/cassandra-data-cassandra-0 (1Gi)
- ido-bcols-dev/cassandra-data-cassandra-1 (1Gi)
- ido-bcols-dev/cassandra-data-cassandra-2 (1Gi)

**Comment by ll911** [comment]
@jefkel done. you can close this one.
