### ISSUE TITLE
ll-realm Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#29]
### List of affected namespaces:
- ll-realm

### List of volumes to migrate:
- ll-realm/gogs-data (5Gi)
- ll-realm/gogs-postgres-data (20Gi)
- ll-realm/kong (1Gi)
- ll-realm/mongo-claim0 (1Gi)

**Comment by kelpisland** [comment]
I think these are @ll911 ‘s

**Comment by ll911** [comment]
@jefkel this one is done, you can close this one.
