### ISSUE TITLE
databcdc Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#3]
### List of affected namespaces:
- databcdc

### List of volumes to migrate:
- databcdc/bcdc-conf (1Gi)
- databcdc/bcdc-filestore (1Gi)
- databcdc/postgresql (5Gi)
- databcdc/solr (1Gi)
- databcdc/solr-logs (1Gi)

**Comment by ll911** [comment]
done. @jefkel you can close this one.
