### ISSUE TITLE
mem-mmt Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#30]
### List of affected namespaces:
- mem-mmt-tools
- mem-mmt-dev
- mem-mmt-test
- mem-mmt-prod

### List of volumes to migrate:
- mem-mmt-tools/jenkins-pipeline-svc (1Gi)
- mem-mmt-dev/mem-admin-dev-docs-pvc (5Gi)
- mem-mmt-dev/mem-mmt-dev-docs-5gi-pvc (5Gi)
- mem-mmt-test/mem-mmt-test-docs-pvc (100Gi)
- mem-mmt-test/mongodbdata (1Gi)
- mem-mmt-prod/mem-mmt-prod-docs-100gi-pvc (100Gi)
- mem-mmt-prod/mem-mmt-prod-docs-pvc (1Gi)
- mem-mmt-prod/mongodb-backup (50Gi)
- mem-mmt-prod/mongodbdata-10gi-pvc (10Gi)
- mem-mmt-prod/mongodbdata (1Gi)

**Comment by ActionAnalytics** [comment]
DONE -- mem-mmt-tools/jenkins-pipeline-svc (1Gi)
DONE -- mem-mmt-dev/mem-admin-dev-docs-pvc (5Gi)
DONE -- mem-mmt-dev/mem-mmt-dev-docs-5gi-pvc (5Gi)
DONE -- mem-mmt-test/mem-mmt-test-docs-pvc (100Gi)
DONE -- mem-mmt-test/mongodbdata (1Gi)
DONE -- mem-mmt-prod/mem-mmt-prod-docs-100gi-pvc (100Gi)
DONE -- mem-mmt-prod/mem-mmt-prod-docs-pvc (1Gi)
DONE -- mem-mmt-prod/mongodb-backup (50Gi)
DONE -- mem-mmt-prod/mongodbdata-10gi-pvc (10Gi)
DONE -- mem-mmt-prod/mongodbdata (1Gi)

**Comment by ActionAnalytics** [comment]
Can you re-run your scan please?  We noticed some old storage still in use but not in the list.  I'd like to confirm those are ok.

**Comment by jefkel** [comment]
Verified clear
