### ISSUE TITLE
mem-mmti Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#31]
### List of affected namespaces:
- mem-mmti-tools
- mem-mmti-dev
- mem-mmti-test
- mem-mmti-prod

### List of volumes to migrate:
- mem-mmti-tools/jenkins (1Gi)
- mem-mmti-dev/mmti-dev-docs-pvc (1Gi)
- mem-mmti-dev/mongodbdata (5Gi)
- mem-mmti-test/mmti-test-docs-pvc (1Gi)
- mem-mmti-test/mongodbdata (1Gi)
- mem-mmti-prod/mmti-prod-docs-pvc (1Gi)
- mem-mmti-prod/mongodbdata (1Gi)

**Comment by ActionAnalytics** [comment]
DONE -- mem-mmti-tools/jenkins (1Gi)
DONE -- mem-mmti-dev/mmti-dev-docs-pvc (1Gi)
DONE -- mem-mmti-dev/mongodbdata (5Gi)
DONE -- mem-mmti-test/mmti-test-docs-pvc (1Gi)
DONE -- mem-mmti-test/mongodbdata (1Gi)
DONE -- mem-mmti-prod/mmti-prod-docs-pvc (1Gi)
DONE -- mem-mmti-prod/mongodbdata (1Gi)

**Comment by jefkel** [comment]
verified complete
