### ISSUE TITLE
moe-land-designations Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#33]
### List of affected namespaces:
- moe-land-designations-tools
- moe-land-designations-dev
- moe-land-designations-test
- moe-land-designations-prod

### List of volumes to migrate:
- moe-land-designations-tools/jenkins-pipeline-svc (1Gi)
- moe-land-designations-tools/rshiny-bookmarks-pvc (1Gi)
- moe-land-designations-tools/rshiny-docs-pvc (1Gi)
- moe-land-designations-tools/rshiny-logs-pvc (1Gi)
- moe-land-designations-dev/rshiny-bookmarks-pvc (1Gi)
- moe-land-designations-dev/rshiny-docs-pvc (1Gi)
- moe-land-designations-dev/rshiny-logs-pvc (1Gi)
- moe-land-designations-test/rshiny-bookmarks-pvc (1Gi)
- moe-land-designations-test/rshiny-docs-pvc (1Gi)
- moe-land-designations-test/rshiny-logs-pvc (1Gi)
- moe-land-designations-prod/rshiny-bookmarks-pvc (1Gi)
- moe-land-designations-prod/rshiny-docs-pvc (1Gi)
- moe-land-designations-prod/rshiny-logs-pvc (1Gi)

**Comment by ateucher** [comment]
HI @jefkel - @sheaphillips reached out to me earlier about this now defunct project. At that time I gave him the go-ahead to decommission it entirely. So do whatever you need to!

**Comment by ShellyXueHan** [comment]
@jefkel @ateucher @sheaphillips `moe-land-designations-*` namespaces deleted as requested.
