### ISSUE TITLE
ontvon-von Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#37]
### List of affected namespaces:
- ontvon-von-prod

### List of volumes to migrate:
- ontvon-von-prod/backup-pvc (840Gi)

### Post migration items:
- Review/update Storage Quota

**Comment by kelpisland** [comment]
I’m assuming @WadeBarnes can help with this one

**Comment by jefkel** [comment]
nfs-backup storagclass quota has been increased in this project and is ready for you to provision  @WadeBarnes.

**Comment by WadeBarnes** [comment]
New nfs-backup volume created;
```$ oc get pvc -n ontvon-von-prod
NAME                              STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
backup-pvc                        Bound     app-pv-265-840g                            840Gi      RWO,RWX        manual-storage    131d
bk-ontvon-von-prod-62av4picizcy   Bound     ontvon-von-prod-62av4picizcy               840Gi      RWX            nfs-backup        25m
django                            Bound     pvc-bba3d9c9-c7d7-11e8-bbed-0050568379a2   1Gi        RWO            gluster-file      138d
postgresql                        Bound     pvc-831f3ba3-c7d7-11e8-bbed-0050568379a2   70Gi       RWO            gluster-file-db   138d
solr                              Bound     pvc-8837fdd3-c7d7-11e8-bbed-0050568379a2   12Gi       RWO            gluster-file      138d
wallet-db                         Bound     pvc-b85d97e4-c814-11e8-bbed-0050568379a2   350Gi      RWO            gluster-file-db   137d
```

Backups running.  I'm going to let it run for a couple days and then I'll delete the old PVC `backup-pvc`.

**Comment by kelpisland** [comment]
👍

Product Director, Enterprise DevOps
BC Developers’ Exchange
OCIO
Province of British Columbia
(250)-217-5639<tel:(250)-217-5639>

On Feb 19, 2019, at 11:40 AM, Wade Barnes <notifications@github.com<mailto:notifications@github.com>> wrote:


New nfs-backup volume created;

NAME                              STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
backup-pvc                        Bound     app-pv-265-840g                            840Gi      RWO,RWX        manual-storage    131d
bk-ontvon-von-prod-62av4picizcy   Bound     ontvon-von-prod-62av4picizcy               840Gi      RWX            nfs-backup        25m
django                            Bound     pvc-bba3d9c9-c7d7-11e8-bbed-0050568379a2   1Gi        RWO            gluster-file      138d
postgresql                        Bound     pvc-831f3ba3-c7d7-11e8-bbed-0050568379a2   70Gi       RWO            gluster-file-db   138d
solr                              Bound     pvc-8837fdd3-c7d7-11e8-bbed-0050568379a2   12Gi       RWO            gluster-file      138d
wallet-db                         Bound     pvc-b85d97e4-c814-11e8-bbed-0050568379a2   350Gi      RWO            gluster-file-db   137d


Backups running. I'm going to let it run for a couple days and then I'll delete the old PVC backup-pvc.

**Comment by WadeBarnes** [comment]
Manual backup storage has been released.

```
$ oc get pvc -n ontvon-von-prod
NAME                              STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
bk-ontvon-von-prod-62av4picizcy   Bound     ontvon-von-prod-62av4picizcy               840Gi      RWX            nfs-backup        2d
django                            Bound     pvc-bba3d9c9-c7d7-11e8-bbed-0050568379a2   1Gi        RWO            gluster-file      141d
postgresql                        Bound     pvc-831f3ba3-c7d7-11e8-bbed-0050568379a2   70Gi       RWO            gluster-file-db   141d
solr                              Bound     pvc-8837fdd3-c7d7-11e8-bbed-0050568379a2   12Gi       RWO            gluster-file      141d
wallet-db                         Bound     pvc-b85d97e4-c814-11e8-bbed-0050568379a2   350Gi      RWO            gluster-file-db   140d
```
