### ISSUE TITLE
opsteam-operations Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#38]
### List of affected namespaces:
- opsteam-operations-tools
- opsteam-operations-dev
- opsteam-operations-test

### List of volumes to migrate:
- opsteam-operations-tools/mongodb (1Gi)
- opsteam-operations-dev/grafana-persistence (1Gi)
- opsteam-operations-dev/grafana-plugins (1Gi)
- opsteam-operations-dev/influxdb-persistence (5Gi)
- opsteam-operations-test/grafana-persistence (1Gi)
- opsteam-operations-test/grafana-plugins (1Gi)
- opsteam-operations-test/pvc-gp3yj (5Gi)

**Comment by sheaphillips** [comment]
I had @ShellyXueHan remove these too. Can close this issue.
