### ISSUE TITLE
pwtest2 Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#39]
### List of affected namespaces:
- pwtest2

### List of volumes to migrate:
- pwtest2/d1 (1Gi)
- pwtest2/mysql (1Gi)

**Comment by kelpisland** [comment]
Pretty sure we can delete this whole namespace and all objects, but I’ll check with Peter.

**Comment by jefkel** [comment]
Project deleted as per Todd's request.
