### ISSUE TITLE
dbc-cms-vis Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#4]
### List of affected namespaces:
- dbc-cms-vis-tools

### List of volumes to migrate:
- dbc-cms-vis-tools/mongodb (1Gi)
- dbc-cms-vis-tools/wiki-data (1Gi)
- dbc-cms-vis-tools/wiki-logs (1Gi)
- dbc-cms-vis-tools/wiki-repo (1Gi)

**Comment by ll911** [comment]
done, @jefkel you can close this one.
