### ISSUE TITLE
servicebc-cfms Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#40]
### List of affected namespaces:
- servicebc-cfms-prod

### List of volumes to migrate:
- servicebc-cfms-prod/datadir-percona-0 (5Gi)
- servicebc-cfms-prod/datadir-percona-1 (5Gi)
- servicebc-cfms-prod/datadir-percona-2 (5Gi)
- servicebc-cfms-prod/lockdir (1Gi)
- servicebc-cfms-prod/rabbitmq-rabbitmq-0 (1Gi)
- servicebc-cfms-prod/rabbitmq-rabbitmq-1 (1Gi)
- servicebc-cfms-prod/rabbitmq-rabbitmq-2 (1Gi)

**Comment by gil0109** [comment]
Completed:

* servicebc-cfms-prod/lockdir (1Gi)
* servicebc-cfms-prod/rabbitmq-rabbitmq-0 (1Gi)
* servicebc-cfms-prod/rabbitmq-rabbitmq-1 (1Gi)
* servicebc-cfms-prod/rabbitmq-rabbitmq-2 (1Gi)

**Comment by jefkel** [comment]
update fr slack (@gil0109 ):
successfully migrated Percona stateful set.  I will leave it running for a couple of days before I delete the old PVCs.

**Comment by gil0109** [comment]
@jefkel I have deleted the PVCs.  Please close the issue.
