### ISSUE TITLE
servicebc-customer-flow Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#41]
### List of affected namespaces:
- servicebc-customer-flow-tools

### List of volumes to migrate:
- servicebc-customer-flow-tools/jenkins (1Gi)
- servicebc-customer-flow-tools/postgresql (5Gi)
- servicebc-customer-flow-tools/sonarqube-data (1Gi)

**Comment by gil0109** [comment]
Project space has been removed.  PVs are no longer used.
