### ISSUE TITLE
Release T3 storage

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/StorageMigration#45]
Each gluster host has 1400G of T3 storage that can be released once a few PVs are cleared.

- [x] #8 devex-von-bc-tob Storage Migration
- [x] #37 ontvon-von Storage Migration
- [x] iStore order to release storage

**Comment by StevenBarre** [comment]
@WadeBarnes For this we only care about 8 and 37 since they are on T3 instead of T2. It's a separate disk we can release early before the rest of the pvcs get migrated.

@lukegonis I'll get you the stuff for the iStore next week once the Registry is moved and we can release that as well.

**Comment by jefkel** [comment]
Confirmed with Luke, iStore request completed.
