### ISSUE TITLE
dbc-mapsdk Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#5]
### List of affected namespaces:
- dbc-mapsdk-tools

### List of volumes to migrate:
- dbc-mapsdk-tools/couchdb-data (1Gi)

**Comment by ll911** [comment]
done, @jefkel  you can close this one.

**Comment by jefkel** [comment]
PV looks like it's still bound to your PVC

**Comment by ll911** [comment]
@jefkel forgot to remove pvc, it's done now.
