### ISSUE TITLE
devex-platform Storage Migration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/StorageMigration#6]
### List of affected namespaces:
- devex-platform-dev
- devex-platform-test
- devex-platform-prod

### List of volumes to migrate:
- devex-platform-dev/mongodbdata (5Gi)
- devex-platform-dev/platform-dev-docs-pvc (1Gi)
- devex-platform-prod/mongodbdata (5Gi)
- devex-platform-prod/platform-prod-docs-pvc (1Gi)
- devex-platform-test/mongodbdata (5Gi)
- devex-platform-test/platform-test-docs-pvc (1Gi)

**Comment by sutherlanda** [comment]
Done.
